name: Continuous Integration Laravel
on:
  push:
    branches:
      - master
jobs:
  laravel-continuous-deployment:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: [7.4,8.1]
        node_version:
          - 12
          - 14
    #name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: 'cd /var/www/movieapp.kofi.work/public_html'

      - name: Install Node dependencies
        run: npm install


      - name: Install Composer dependencies
        run: composer install --no-interaction --no-suggest --ignore-platform-reqs







