jobs:
  ci:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: [8.1, 8.2]
        node_version: [14, 16]
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: 'cd /var/www/movieapp.kofi.work/public_html && sudo chmod 777 deploy.sh && ./deploy.sh'
