name: Continuous Integration Laravel
on:
  push:
    branches:
      - production
jobs:
  laravel-continuous-deployment:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: [7.4]
        node_version:
          - 12
          - 14
    #name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Node dependencies
        run: npm install

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-suggest --ignore-platform-reqs





